<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>axios基本使用</title>
    <link crossorigin="anonymous" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/axios/1.0.0-alpha.1/axios.min.js"></script>
</head>
<body>
<div class="container">
    <h2 class="page-header">基本使用</h2>
    <button class="btn btn-primary">发送GET请求</button>
    <button class="btn btn-warning">发送POST请求</button>
</div>

<script>

    // 请求拦截器 - 1
    axios.interceptors.request.use(function (config) {
        // 请求发送之前做一些事情
        console.log("请求成功   -  请求测试1111")
        return config;
    }, function (error) {
        // Do something with request error
        console.log("请求失败   -  请求测试1111")
        return Promise.reject(error);
    });

    // 请求拦截器  - 2
    axios.interceptors.request.use(function (config) {
        // 请求发送之前做一些事情
        console.log("请求成功   --- 请求测试22222")
        return config;
    }, function (error) {
        // Do something with request error
        console.log("请求失败   --- 请求测试22222")
        return Promise.reject(error);
    });

    // 响应拦截器 - 1
    axios.interceptors.response.use(function (response) {
        // Any status code that lie within the range of 2xx cause this function to trigger
        // Do something with response data
        console.log("响应成功       响应测试- 11111")
        return response;
    }, function (error) {
        // Any status codes that falls outside the range of 2xx cause this function to trigger
        // Do something with response error
        console.log("响应失败       响应测试- 11111")
        return Promise.reject(error);
    });

    // 响应拦截器 - 2
    axios.interceptors.response.use(function (response) {
        // Any status code that lie within the range of 2xx cause this function to trigger
        // Do something with response data
        console.log("响应成功   -      响应测试2222")
        return response;
    }, function (error) {
        // Any status codes that falls outside the range of 2xx cause this function to trigger
        // Do something with response error
        console.log("响应失败   -      响应测试2222")
        return Promise.reject(error);
    });

    axios.request({
        method: 'GET',
        url: 'http://localhost:3000/posts'
    }).then(response=>{
        console.log(response)
    }).catch(reason=>{
        console.log("请求失败测试")
    })


</script>
</body>
</html>